Repository shivansh-bhatnagar18/multiplayer-uno, pull requests merged in 2024-06, with the labels that each got.

#33 engine: Convert to typescript
  backend/src/types.d.ts
  backend/uno-game-engine/engine.ts
Labels: approved: Kislay

#14 deck: Assigned unique id to each card.
  backend/src/types.d.ts
  backend/uno-game-engine/deck.ts
Labels: approved: Kislay

#30 deck: completed function to create and shuffle a UNO card deck.
  backend/src/types.d.ts
  backend/tests/deck.test.ts
  backend/uno-game-engine/deck.ts
Labels: under review

#59 ErrorPage: created 404 Page Not Found page
  frontend/src/assets/tornCard.svg
  frontend/src/pages/Error.tsx
Labels: approved: Shivansh, approved: Apoorv, area: Frontend (design)

#70 Designed a Toast Component
  frontend/src/library/toast/Toast.tsx
  frontend/src/library/toast/toast-context.ts
  frontend/src/library/toast/toast.css
  frontend/src/main.tsx
Labels: area: Frontend, area: Frontend (design), under review

#75 Frontend: Added a customizable and reusable heading component
  frontend/src/library/heading.tsx
  frontend/src/pages/PlayOptions.tsx
Labels: can be merged, approved: Kislay

#57 Server: Route Handler for /event
  backend/src/controllers/gameControllers.js
  backend/src/eventRecipients.ts
  backend/src/routes/gameRoutes.js
Labels: under review

#83 Frontend: designed a custom button component based on figma design
  frontend/src/index.css
  frontend/src/library/button.tsx
  frontend/src/pages/PlayOptions.tsx
  frontend/tailwind.config.js
Labels: can be merged, approved: Kislay, area: Frontend (design)

#64 client:Implemented the enqueuing mechanism for clients
  backend/src/eventRecipients.ts
Labels: can be merged soon

#50 gameEvent: Implement Throw Card Event
  ARCHITECTURE.md
  backend/src/uno-game-engine/engine.ts
  backend/src/uno-game-engine/events/throwCard.ts
  backend/tests/engine.test.ts
Labels: area: Backend(Game Engine), priority: high, under review

#105 Frontend: Implemented the gamepage and GameContext
  frontend/public/cardPool.png
  frontend/public/card_faces/back.jpeg
  frontend/public/deckMat.png
  frontend/public/playBackground.png
  frontend/public/playerIcon.png
  frontend/src/App.tsx
  frontend/src/contexts/GameContext.tsx
  frontend/src/pages/Game.tsx
  frontend/src/pages/Home.tsx
  frontend/tailwind.config.js
Labels: approved: Shivansh

#118 Client: Added a Scrollbar
  frontend/src/index.css
Labels: area: Frontend (design)
